DROP TABLE IF EXISTS SGT_ACCOUNT CASCADE;
DROP TABLE IF EXISTS SGT_MENU CASCADE;
DROP TABLE IF EXISTS SGT_TUMBLER CASCADE;
DROP TABLE IF EXISTS SGT_PRIVATE_MENU CASCADE;
DROP TABLE IF EXISTS SGT_PERSONAL_OPTION CASCADE;
DROP TABLE IF EXISTS SGT_ORDER CASCADE;
DROP TABLE IF EXISTS SGT_ORDERDETAILS CASCADE;

DROP SEQUENCE IF EXISTS SGT_MENU_SEQ;
DROP SEQUENCE IF EXISTS SGT_TUMBLER_SEQ;
DROP SEQUENCE IF EXISTS SGT_OPTION_SEQ;
DROP SEQUENCE IF EXISTS SGT_ORDER_SEQ;
DROP SEQUENCE IF EXISTS SGT_PRIVATE_MENU_SEQ;

CREATE SEQUENCE SGT_MENU_SEQ 			START 1;
CREATE SEQUENCE SGT_TUMBLER_SEQ 			START 1;
CREATE SEQUENCE SGT_OPTION_SEQ			START 1;
CREATE SEQUENCE SGT_ORDER_SEQ			START 1;
CREATE SEQUENCE SGT_PRIVATE_MENU_SEQ		START 1;


CREATE TABLE SGT_ACCOUNT (
    ACCOUNT_ID	VARCHAR PRIMARY KEY,
    PWD             	VARCHAR,
    NICKNAME    VARCHAR,
    STAR_TYPE	VARCHAR,
    STAR_CNT        NUMERIC
);


 
CREATE TABLE SGT_MENU (
	MENU_ID 		NUMERIC PRIMARY KEY,
	CATEGORY1		VARCHAR,
	CATEGORY2		VARCHAR,
	MENU_NAME		VARCHAR,
	SIZE			VARCHAR,
	PRICE			NUMERIC
);

CREATE TABLE SGT_PRIVATE_MENU (
	PRIVATE_MENU_ID	NUMERIC PRIMARY KEY,
	CUP				VARCHAR,
	ACCOUNT_ID		VARCHAR REFERENCES SGT_ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
	MENU_ID			NUMERIC REFERENCES SGT_MENU(MENU_ID) ON DELETE CASCADE,
	SHOT			NUMERIC,
	SYRUP			NUMERIC,
	WHIPPED_CREAM	BOOLEAN,
	DRIZZLE			BOOLEAN,
	SIZE			VARCHAR,
	OPTION_SUM		NUMERIC,
	PRICE			NUMERIC
);

CREATE TABLE SGT_TUMBLER (
	TUMBLER_ID		NUMERIC PRIMARY KEY,
	NFC_ID			VARCHAR UNIQUE,
	ACCOUNT_ID 		VARCHAR REFERENCES SGT_ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
	TUMBLER_NAME		VARCHAR,
	TUMBLER_PIN		NUMERIC,
	SIZE			VARCHAR,--Q
	TUMBLER_MONEY		NUMERIC,
	GREEN_SEED		NUMERIC,
	LOST_YN			BOOLEAN DEFAULT FALSE,
	PAY_YN			BOOLEAN,
	PRIVATE_MENU_ID		NUMERIC REFERENCES SGT_PRIVATE_MENU(PRIVATE_MENU_ID) ON DELETE CASCADE
);



CREATE TABLE SGT_ORDER (
	ORDER_ID 		NUMERIC PRIMARY KEY,
	ACCOUNT_ID		VARCHAR REFERENCES SGT_ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
	ORDER_TIME		TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRICE			NUMERIC,
	STORE_NAME		VARCHAR DEFAULT '남산스테이트점',
	TUMBLER_ID		NUMERIC REFERENCES SGT_TUMBLER(TUMBLER_ID) ON DELETE CASCADE
);

CREATE TABLE SGT_ORDERDETAILS (
	ORDER_ID		NUMERIC NOT NULL REFERENCES SGT_ORDER(ORDER_ID) ON DELETE CASCADE,
	LINE_ID			NUMERIC,
	PRIVATE_MENU_YN	BOOLEAN,
	PRIVATE_MENU_ID NUMERIC REFERENCES SGT_PRIVATE_MENU(PRIVATE_MENU_ID) ON DELETE CASCADE,
	MENU_ID			NUMERIC REFERENCES SGT_MENU(MENU_ID) ON DELETE CASCADE,
	IS_TUMBLER		BOOLEAN,
	SHOT			NUMERIC DEFAULT 0,
	SYRUP			NUMERIC DEFAULT 0,
	WHIPPED_CREAM		BOOLEAN DEFAULT FALSE,
	DRIZZLE			BOOLEAN DEFAULT FALSE,
	SIZE			VARCHAR,
	OPTION_SUM		NUMERIC DEFAULT 0,
	MENU_CNT		NUMERIC DEFAULT 1,
	PRICE			NUMERIC,

	CONSTRAINT PF PRIMARY KEY (ORDER_ID, LINE_ID)
);


-- USER DUMMY
INSERT INTO SGT_ACCOUNT VALUES ( 'test', 'test', 'testuser', 'gold', 1);

INSERT INTO SGT_TUMBLER VALUES ( NEXTVAL('SGT_TUMBLER_SEQ'), '0002360456', 'test', 'test_sgt', '0002360456', 1, 40000, 3, FALSE, TRUE );

-- MENU DUMMY
-- ESPRESSO
INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '에스프레소', '아이스 카페 아메리카노', 1, 4100);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '에스프레소', '에스프레소', 1, 3600);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '에스프레소', '아이스 카페모카', 1, 5100 );

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '에스프레소', '아이스 카페라떼', 1, 4600);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '에스프레소', '아이스 카푸치노', 1, 5100);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '에스프레소', '돌체 콜드 브루', 1, 5800);

-- 프라푸치노
INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '프라푸치노', '모카 프라푸치노', 1, 6300);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '프라푸치노', '아몬드 모카 프라푸치노', 1, 7000);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '프라푸치노', '에스프레소 프라푸치노', 1, 6500);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '프라푸치노', '카라멜 프라푸치노', 1, 7200);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '프라푸치노', '바닐라 크림 프라푸치노', 1, 7000);

-- 블랜디드
INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '블렌디드', '디카페인 아포가토 블렌디드', 1, 6100);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '블렌디드', '망고 패션 후르츠 블렌디드', 1, 5000);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '블렌디드', '제주 호두 당근 블랜디드', 1, 6000);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '블렌디드', '딸기 요거트 블랜디드', 1, 6100);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '블렌디드', '망고 바나나 블랜디드', 1, 6300);

-- 피지오
INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '피지오', '블랙 티 레모네이드 피지오', 1, 5400);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '피지오', '쿨 라임 피지오', 1, 5900);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '피지오', '핑크 자몽 피지오', 1, 6300);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '피지오', '패션 탱고 티 레모네이드 피지오', 1, 5400);

-- 티
INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '티', '말차 레모네이드', 1, 6100);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '티', '별다방 아이스 티', 1, 5600);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '티', '핑크베리 유스베리', 1, 7100);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '티', '말차 레모네이드', 1, 6100);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '티', '그랜마 애플 블랙 티', 1, 7500);

INSERT INTO SGT_MENU (MENU_ID, CATEGORY1, CATEGORY2, MENU_NAME, SIZE, PRICE)
VALUES (NEXTVAL('SGT_MENU_SEQ'), '음료', '티', '라임 패션 티', 1, 5300);

--주문정보(헤더)
INSERT INTO SGT_ORDER VALUES ( 2019082301, 'test', '20190823', 6100, '남산스테이트점', 1 );
INSERT INTO SGT_ORDER VALUES ( 2019082302, 'test', '20190823', 4100, '남산스테이트점', 1 );

--주문정보(디테일)
INSERT INTO SGT_ORDERDETAILS (ORDER_ID, LINE_ID, PRIVATE_MENU_YN, PRIVATE_MENU_ID, MENU_ID, IS_TUMBLER, SIZE, PRICE) VALUES ( 2019082301, 1, FALSE, NULL, 24, TRUE, 'T', 6100);
INSERT INTO SGT_ORDERDETAILS (ORDER_ID, LINE_ID, PRIVATE_MENU_YN, PRIVATE_MENU_ID, MENU_ID, IS_TUMBLER, SIZE, PRICE) VALUES ( 2019082302, 1, FALSE, NULL, 1, TRUE, 'T', 4100);

--나만의 메뉴
INSERT INTO SGT_PRIVATE_MENU 
(PRIVATE_MENU_ID, CUP, ACCOUNT_ID, MENU_ID, SHOT, SYRUP, WHIPPED_CREAM, DRIZZLE, SIZE, OPTION_SUM, PRICE)
VALUES
(NEXTVAL('SGT_PRIVATE_MENU_SEQ'), 'T', 'test', 2, 1, 1, false, false, 'T', 1200, 5300);

INSERT INTO SGT_PRIVATE_MENU 
(PRIVATE_MENU_ID, CUP, ACCOUNT_ID, MENU_ID, SHOT, SYRUP, WHIPPED_CREAM, DRIZZLE, SIZE, OPTION_SUM, PRICE)
VALUES
(NEXTVAL('SGT_PRIVATE_MENU_SEQ'), 'T', 'test', 7, 0, 1, true, false, 'G', 1200, 6000);

COMMIT;
